apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:  myapp
  labels:
    app:  myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app:  myapp
    spec:
      containers:
      - name:  nginx-container
        image:  nginx
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
